export type { VideoJsPlayer } from './type'
export type { PropsConfig, PropKey, Props } from './props'
export type { EventMap, EventKey, CamelCaseEventKey } from './events'
export type { CreatePlayerStateOptions, PlayerState } from './state'
export type { CreatePlayerOptions, PlayerResult } from './player'

export { propsConfig, propKeys } from './props'
export { eventsMap, events, camelCaseEvents } from './events'
export { createPlayer } from './player'
export { createPlayerState } from './state'
